wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    session_history: code/_session_history.ipynb
    start_time: 1645261525
    t:
      3:
      - 2
      - 13
      - 15
      - 16
      4: 3.8.5
      5: 0.12.10
      8:
      - 1
      - 5
changepoint:
  desc: null
  value: 0.09999999999999999
daily:
  desc: null
  value: 10
holiday:
  desc: null
  value: 10
seasonality:
  desc: null
  value: 10
weekly:
  desc: null
  value: 10
